### ISSUE TITLE
Keep User logged in

### ISSUE THREAD

**Issue by tb0se** [CodeFusionGroup/GradsHub#17]
Using Shared Preferences to keep user logged in but its a bit buggy and shows the log in screen for like a second.

**Comment by bakang-dev** [comment]
Unable to see the behavior described but do notice a very brief delay (that doesn't show any screen) before home screen is shown or login screen is shown based on the login state of the user. This delay could just be that the app is reading preferences file and doing a check and these operations aren't instantaneous even though "apply" is used instead of "commit" to perform the operations asynchronously.
